# TCL File Generated by Component Editor 25.3
# DO NOT MODIFY

package require -exact qsys 25.3

set_module_property DESCRIPTION ""
set_module_property NAME axi_core_hw
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME axi_core_hw
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false

add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi_core_hw
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file alu.sv SYSTEM_VERILOG PATH alu.sv
add_fileset_file regfile.sv SYSTEM_VERILOG PATH regfile.sv
add_fileset_file decoder.sv SYSTEM_VERILOG PATH decoder.sv
add_fileset_file riscv_soc.sv SYSTEM_VERILOG PATH riscv_soc.sv
add_fileset_file axi_core_hw.sv SYSTEM_VERILOG PATH axi_core_hw.sv TOP_LEVEL_FILE

add_interface axm_m0 axi4 start
set_interface_property axm_m0 associatedClock clock
set_interface_property axm_m0 associatedReset reset
set_interface_property axm_m0 readIssuingCapability 1
set_interface_property axm_m0 writeIssuingCapability 1
set_interface_property axm_m0 combinedIssuingCapability 1
set_interface_property axm_m0 ENABLED true

add_interface_port axm_m0 axm_m0_awid awid Output 4
add_interface_port axm_m0 axm_m0_awaddr awaddr Output 64
add_interface_port axm_m0 axm_m0_awlen awlen Output 8
add_interface_port axm_m0 axm_m0_awprot awprot Output 3
add_interface_port axm_m0 axm_m0_awvalid awvalid Output 1
add_interface_port axm_m0 axm_m0_awready awready Input 1
add_interface_port axm_m0 axm_m0_wdata wdata Output 1024
add_interface_port axm_m0 axm_m0_wlast wlast Output 1
add_interface_port axm_m0 axm_m0_wvalid wvalid Output 1
add_interface_port axm_m0 axm_m0_wready wready Input 1
add_interface_port axm_m0 axm_m0_bid bid Input 4
add_interface_port axm_m0 axm_m0_bvalid bvalid Input 1
add_interface_port axm_m0 axm_m0_bready bready Output 1
add_interface_port axm_m0 axm_m0_arid arid Output 4
add_interface_port axm_m0 axm_m0_araddr araddr Output 64
add_interface_port axm_m0 axm_m0_arlen arlen Output 8
add_interface_port axm_m0 axm_m0_arprot arprot Output 3
add_interface_port axm_m0 axm_m0_arvalid arvalid Output 1
add_interface_port axm_m0 axm_m0_arready arready Input 1
add_interface_port axm_m0 axm_m0_rid rid Input 4
add_interface_port axm_m0 axm_m0_rdata rdata Input 1024
add_interface_port axm_m0 axm_m0_rlast rlast Input 1
add_interface_port axm_m0 axm_m0_rvalid rvalid Input 1
add_interface_port axm_m0 axm_m0_rready rready Output 1

add_interface clock clock end
set_interface_property clock ENABLED true
add_interface_port clock clk clk Input 1

add_interface cpu_clock clock end
set_interface_property cpu_clock ENABLED true
add_interface_port cpu_clock cpu_clk clk Input 1

add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
add_interface_port reset rst reset Input 1

add_interface axi_lite_s axi4lite end
set_interface_property axi_lite_s associatedClock clock
set_interface_property axi_lite_s associatedReset reset
set_interface_property axi_lite_s readAcceptanceCapability 1
set_interface_property axi_lite_s writeAcceptanceCapability 1
set_interface_property axi_lite_s combinedAcceptanceCapability 1
set_interface_property axi_lite_s ENABLED true

add_interface_port axi_lite_s axi_lite_s_awaddr awaddr Input 22
add_interface_port axi_lite_s axi_lite_s_awvalid awvalid Input 1
add_interface_port axi_lite_s axi_lite_s_awready awready Output 1
add_interface_port axi_lite_s axi_lite_s_wdata wdata Input 64
add_interface_port axi_lite_s axi_lite_s_wstrb wstrb Input 8
add_interface_port axi_lite_s axi_lite_s_wvalid wvalid Input 1
add_interface_port axi_lite_s axi_lite_s_wready wready Output 1
add_interface_port axi_lite_s axi_lite_s_bvalid bvalid Output 1
add_interface_port axi_lite_s axi_lite_s_bready bready Input 1
add_interface_port axi_lite_s axi_lite_s_araddr araddr Input 22
add_interface_port axi_lite_s axi_lite_s_arvalid arvalid Input 1
add_interface_port axi_lite_s axi_lite_s_arready arready Output 1
add_interface_port axi_lite_s axi_lite_s_rdata rdata Output 64
add_interface_port axi_lite_s axi_lite_s_rvalid rvalid Output 1
add_interface_port axi_lite_s axi_lite_s_rready rready Input 1
